/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_paulinaeuceda;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author euced
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form PracticaG
     */
    public Main() {

        nombre = "Tulio";
        initComponents();
        dc_fecha.setDate(new Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_chat = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_contactos = new javax.swing.JList<>();
        jb_send = new javax.swing.JButton();
        ta_maquina = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_chat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jd_registrar = new javax.swing.JDialog();
        tf_username = new javax.swing.JTextField();
        tf_display = new javax.swing.JTextField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pf_contrasena = new javax.swing.JPasswordField();
        jb_crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_userL = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jb_ingresar = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();

        jd_chat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_contactos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_contactos);

        jd_chat.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 155, 223));

        jb_send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/send.png"))); // NOI18N
        jb_send.setText("Enviar");
        jb_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_sendMouseClicked(evt);
            }
        });
        jd_chat.getContentPane().add(jb_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 110, 40));
        jd_chat.getContentPane().add(ta_maquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 540, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_chat.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, 40));

        ta_chat.setColumns(20);
        ta_chat.setRows(5);
        jScrollPane1.setViewportView(ta_chat);

        jd_chat.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 450, 220));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Contactos");
        jd_chat.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Conversación");
        jd_chat.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Teclado");
        jd_chat.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/free-blurry-background-1636594.jpg"))); // NOI18N
        jd_chat.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        jd_registrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_registrar.getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 30));
        jd_registrar.getContentPane().add(tf_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, 30));
        jd_registrar.getContentPane().add(dc_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 150, 40));

        jLabel2.setText("Nombre completo");
        jd_registrar.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("Contraseña");
        jd_registrar.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel4.setText("Usuario");
        jd_registrar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel5.setText("Fecha de Nacimiento");
        jd_registrar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));
        jd_registrar.getContentPane().add(pf_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jb_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sign-up.png"))); // NOI18N
        jb_crear.setText("Registrar");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jb_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 150, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papers.co-se68-blurry-background-sunrise-gradation-blur-40-wallpaper.jpg"))); // NOI18N
        jd_registrar.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("¿No tienes cuenta? Registrate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(tf_userL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 230, 30));
        getContentPane().add(pf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 230, 20));

        jb_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tick.png"))); // NOI18N
        jb_login.setText("Log in");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        getContentPane().add(jb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 110, 30));

        jb_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sign-up.png"))); // NOI18N
        jb_ingresar.setText("Registrate");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(jb_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 130, 40));

        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        getContentPane().add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:

        administrarContactos ap = new administrarContactos("./Users.txt");
        ap.cargarArchivo();

        ArrayList o = ap.getListaContactos();

        DefaultListModel modelo = new DefaultListModel();

        System.out.println(o);

        for (int i = 0; i < o.size(); i++) {
            modelo.addElement(o.get(i));
        }

        jl_contactos.setModel(modelo);

        for (int i = 0; i < o.size(); i++) {
            if (((Contactos) o.get(i)).getDisplay().equals(tf_userL.getText()) && ((Contactos) o.get(i)).getContrasena().equals(pf_contra.getText())) {
                JOptionPane.showMessageDialog(null, "Se inició sesión con éxito");
                nombre = tf_userL.getText();
                ta_maquina.setText(nombre + ": ");
                jd_chat.pack();
                jd_chat.setModal(true);
                jd_chat.setLocationRelativeTo(this);
                jd_chat.setVisible(true);

                break;
            }
        }
        tf_userL.setText("");
        pf_contra.setText("");

    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:

        jd_registrar.pack();
        jd_registrar.setModal(true);
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);


    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jb_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_sendMouseClicked
        // TODO add your handling code here:

        boolean flag = true;
        oracion = ta_maquina.getText();
        String completa = oracion;
        String todo = oracion.substring(0, oracion.length() - 2);


        int pos = oracion.indexOf(':');
        oracion = oracion.substring(pos + 2, oracion.length());

        int po = oracion.length() - 1;
        String o = oracion;
        String tempo = "";
        for (int i = 0; i < oracion.length() - 1; i++) {
            tempo += oracion.charAt(i);
        }
        System.out.println(tempo);
        oracion = tempo;

        int n = o.charAt(po);

        try {
            int posi = completa.indexOf("4");
            antes = completa.substring(pos+2, posi - 1);
            despues = completa.substring(posi+2, completa.length() - 1);
            n = 52;
        } catch (Exception e) {

        }

        switch (n) {
            case 49:
                Primero();
                break;
            case 50:
                Segundo();
                break;
            case 51:
                Tercero();
                break;
            case 52:
                trabason();
                Cuarto();
                break;
            default:
                JOptionPane.showMessageDialog(null, "No existe esa opcion");
                flag = false;
                break;
        }

        if (flag == true) {
            ta_chat.setText(todo + "\n" + "Maquina: " + cadenaFinal);

            String mensaje = ta_chat.getText();
            String archivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo");
            System.out.println(archivo);
            administradorArchivos aa = new administradorArchivos("./" + archivo + ".txt");
            try {
                aa.escribirArchivo(mensaje);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jb_sendMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_chat.pack();
        jd_chat.setModal(false);
        jd_chat.setLocationRelativeTo(this);
        jd_chat.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked

        String cal = dc_fecha.getDate().toString();
        boolean flagUser = true;
        boolean flagEdad = true;

        administrarContactos l = new administrarContactos("./Users.txt");

        for (int i = 0; i < l.getListaContactos().size(); i++) {
            if (l.getListaContactos().get(i).getDisplay().equals(tf_display.getText())) {
                flagUser = false;
                JOptionPane.showMessageDialog(null, "Ya existe alguien con ese username");
                break;
            }
        }

        Date fecha = new Date();

        if (fecha.getYear() - dc_fecha.getDate().getYear() < 13) {
            JOptionPane.showMessageDialog(null, "Tiene que ser mayor a 13 años");
            flagEdad = false;
        }

        if (flagUser == true && flagEdad == true) {
            Contactos p = new Contactos(tf_username.getText(), pf_contrasena.getText(), tf_display.getText(), cal);
            l.getListaContactos().add(p);
            JOptionPane.showMessageDialog(null, "Usuario creado con exito");

            try {
                l.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

            tf_username.setText("");
            pf_contrasena.setText("");
            tf_display.setText("");

        }

    }//GEN-LAST:event_jb_crearMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_registrar.pack();
        jd_registrar.setModal(false);
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    public void trabason() {
        cadena = antes;

        String o = "";

        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.charAt(i) != ' ') {
                o += cadena.charAt(i);
            }
        }
        cadena = o;

    }

    public void Cuarto() {

        String clave = despues;

        int largo = cadena.length() / clave.length();
        if ((cadena.length()) % clave.length() == 0) {

        } else {
            largo += 2;

        }

        char[][] matriz = new char[largo][clave.length()];
        int con = 0;
        int cont = 0;
        for (int i = 0; i < largo; i++) {
            for (int j = 0; j < clave.length(); j++) {
                if (con < cadena.length() && i > 0) {
                    matriz[i][j] = cadena.charAt(con);
                    System.out.print(matriz[i][j] + " ");
                    con++;
                } else if (con > cadena.length() && i > 0) {
                    matriz[i][j] = ' ';
                }
                if (i == 0) {
                    matriz[i][j] = clave.charAt(cont);
                    cont++;
                    System.out.print(matriz[i][j] + " ");

                }
            }
            System.out.println("");
        }

        char[] original = new char[clave.length()];
        for (int i = 0; i < clave.length(); i++) {
            original[i] = clave.charAt(i);
        }
        Arrays.sort(original);

        cadenaFinal = "";

        int conta = 0;
        while (conta < clave.length()) {
            for (int j = 0; j < clave.length(); j++) {
                if (matriz[0][j] == original[conta]) {
                    for (int i = 1; i < largo; i++) {
                        cadenaFinal += matriz[i][j];
                    }
                    conta++;
                    break;
                }
            }
        }

        System.out.println(cadenaFinal);

        System.out.println("");
        for (int i = 0; i < original.length; i++) {
            System.out.print(original[i] + " ");
        }

    }

    public void Tercero() {
        cadenaFinal = "";
        String cadena = oracion;

        String[] tokenEspacios = cadena.split(" ");

        for (int i = 0; i < tokenEspacios.length; i++) {
            for (int j = 0; j < tokenEspacios[i].length(); j++) {
                int pos;
                int resta;
                int desplazamiento = 0;
                if (tokenEspacios[i].charAt(j) >= 65 && tokenEspacios[i].charAt(j) <= 90) {
                    int letra = tokenEspacios[i].charAt(j);
                    pos = letra - 65;
                    resta = 25 - pos;
                    desplazamiento = 65 + resta;
                } else if (tokenEspacios[i].charAt(j) >= 97 && tokenEspacios[i].charAt(j) <= 122) {
                    int letra = tokenEspacios[i].charAt(j);
                    pos = letra - 97;
                    resta = 25 - pos;
                    desplazamiento = 97 + resta;
                }
                cadenaFinal += (char) desplazamiento;
            }
            cadenaFinal += " ";
        }
    }

    public void Primero() {
        cadenaFinal = "";
        String cadena = oracion;
        cadena = cadena.toLowerCase();

        String[] tokenEspacios = cadena.split(" ");

        for (int i = 0; i < tokenEspacios.length; i++) {
            if (tokenEspacios[i].length() <= 3) {
                cadenaFinal += tokenEspacios[i] + "way" + " ";
            } else {
                int primer = tokenEspacios[i].charAt(0);
                int segundo = tokenEspacios[i].charAt(1);
                char primero = tokenEspacios[i].charAt(0);
                char segundoo = tokenEspacios[i].charAt(1);

                if (((primer != 97) && (segundo != 97)) && ((primer != 101) && (segundo != 101)) && ((primer != 105) && (segundo != 105)) && ((primer != 111) && (segundo != 111)) && ((primer != 117) && (segundo != 117))) {

                    String tempo = "";
                    for (int j = 2; j < tokenEspacios[i].length(); j++) {
                        tempo += tokenEspacios[i].charAt(j);
                    }
                    cadenaFinal += tempo + primero + segundoo + "ay" + " ";
                } else if (((primer != 97)) || ((primer != 101)) || ((primer != 105)) || ((primer != 111)) || ((primer != 117))) {
                    String tempo = "";
                    for (int j = 1; j < tokenEspacios[i].length(); j++) {
                        tempo += tokenEspacios[i].charAt(j);
                    }
                    cadenaFinal += tempo + primero + "ay" + " ";
                }
            }
        }

    }

    public void Segundo() {
        cadenaFinal = "";
        String chain = oracion;
        char c;
        int ascii, num = 0;
        // chain = chain.toLowerCase();
        System.out.print("Maquina: ");
        for (int i = 0; i < chain.length(); i++) {
            c = chain.charAt(i);

            ascii = c;// le asigno ascii el numero de posicion en donde se encuentra la letra
            if (ascii >= 65 && ascii <= 90) {
                num = ascii;
            } else if (ascii >= 97 && ascii <= 122) {// utilizando el
                num = ascii;

            } else if (num == 0) {
                System.out.print("");
            }
            cadenaFinal += num + " ";
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_send;
    private javax.swing.JDialog jd_chat;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JList<String> jl_contactos;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JTextArea ta_chat;
    private javax.swing.JTextField ta_maquina;
    private javax.swing.JTextField tf_display;
    private javax.swing.JTextField tf_userL;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    String nombre, cadenaFinal;
    Scanner lea = new Scanner(System.in);
    String oracion, antes, despues;
    String cadena;
    char[] original;
}
